# Generated by Django 2.2.5 on 2020-02-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0002_auto_20200217_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
