# Generated by Django 2.2.5 on 2020-02-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0007_auto_20200217_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
