# Generated by Django 2.2.5 on 2020-02-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EzFinance_Account', '0009_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('transaction_detail', models.CharField(max_length=50, null=True)),
                ('transaction_debit', models.FloatField(default=0, null=True)),
                ('transaction_credit', models.FloatField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
