# Generated by Django 2.2.5 on 2020-02-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0010_auto_20200227_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='creditcard_num',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
