# Generated by Django 2.2.5 on 2020-03-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0014_fundtransfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundtransfer',
            old_name='transfer_amout',
            new_name='transfer_amount',
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='transfer_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
