# Generated by Django 2.2.5 on 2020-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0015_auto_20200302_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransfer',
            name='transfer_to',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
