# Generated by Django 2.2.5 on 2020-03-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0016_auto_20200303_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='transaction_ref',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
