# Generated by Django 2.2.5 on 2020-03-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0017_transaction_history_transaction_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_history',
            name='transaction_ref',
        ),
    ]
