# Generated by Django 2.2.5 on 2020-03-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0019_expensesmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_type', models.CharField(max_length=20, null=True)),
                ('expenses_date', models.DateField(null=True)),
                ('expenses_amount', models.FloatField(default=0, null=True)),
                ('expenses_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EzFinance_Account.ExpensesManager')),
            ],
        ),
    ]
