# Generated by Django 2.2.5 on 2020-03-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0021_fixeddeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='deposit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
