# Generated by Django 2.2.5 on 2020-03-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0023_auto_20200314_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='maturity_date',
            field=models.DateTimeField(null=True),
        ),
    ]
