# Generated by Django 2.2.5 on 2020-04-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0027_contact_us_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_subject', models.CharField(max_length=100)),
                ('announcement_content', models.CharField(max_length=300)),
                ('announcement_status', models.BooleanField(default=False)),
                ('publish_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
