# Generated by Django 2.2.5 on 2020-04-15 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EzFinance_Account', '0028_general_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_create_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_created_date', models.DateTimeField(auto_now=True)),
                ('job_expiry_date', models.DateField(null=True)),
                ('job_available_day', models.IntegerField(null=True)),
                ('job_request_approval_status', models.BooleanField(default=False)),
                ('job_request_reject_status', models.BooleanField(default=False)),
                ('job_request_reedit_status', models.BooleanField(default=False)),
                ('job_admin_notice', models.CharField(max_length=500, null=True)),
                ('job_employer_name', models.CharField(max_length=50, null=True)),
                ('job_employer_contact_number', models.CharField(max_length=50, null=True)),
                ('job_employer_email', models.EmailField(max_length=254, null=True)),
                ('job_employer_company', models.CharField(max_length=100, null=True)),
                ('job_location', models.CharField(max_length=300, null=True)),
                ('job_general_description', models.CharField(max_length=1000, null=True)),
                ('job_position', models.CharField(max_length=100, null=True)),
                ('job_duties', models.CharField(max_length=500, null=True)),
                ('job_requirement', models.CharField(max_length=1000, null=True)),
                ('job_salary_from', models.IntegerField(null=True)),
                ('job_salary_to', models.IntegerField(null=True)),
                ('job_type', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
