# Generated by Django 2.2.5 on 2020-04-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0029_job_create_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_create_request',
            name='job_salary_from',
        ),
        migrations.RemoveField(
            model_name='job_create_request',
            name='job_salary_to',
        ),
        migrations.AddField(
            model_name='job_create_request',
            name='job_salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
