# Generated by Django 2.2.5 on 2020-04-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0030_auto_20200416_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_create_request',
            name='job_posted_date',
            field=models.DateField(null=True),
        ),
    ]
