# Generated by Django 2.2.5 on 2020-04-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0031_job_create_request_job_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_create_request',
            name='job_available_day',
            field=models.IntegerField(help_text='maximum days for each vacancy is 365 days', null=True),
        ),
    ]
