# Generated by Django 2.2.5 on 2020-04-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0032_auto_20200416_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_create_request',
            name='job_general_description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='job_create_request',
            name='job_requirement',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
