# Generated by Django 2.2.5 on 2020-04-21 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EzFinance_Account', '0033_auto_20200417_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_apply_date', models.DateTimeField(auto_now=True)),
                ('job_applicant_name', models.CharField(max_length=50, null=True)),
                ('job_applicant_email', models.EmailField(max_length=254, null=True)),
                ('job_applicant_contact_number', models.CharField(max_length=50, null=True)),
                ('job_pitch', models.CharField(max_length=1000, null=True)),
                ('job_mark_as_read', models.BooleanField(default=False)),
                ('applicant_resume', models.FileField(null=True, upload_to='vacancy_resume')),
                ('job_post_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_list', to='EzFinance_Account.Job_create_request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
