# Generated by Django 2.2.5 on 2020-04-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EzFinance_Account', '0035_job_apply_job_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_apply',
            name='applicant_resume',
            field=models.FileField(default='pdf_default.png', null=True, upload_to='vacancy_resume'),
        ),
    ]
