# Generated by Django 2.2.5 on 2020-02-23 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_remove_account_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_detail',
            fields=[
                ('account_id', models.IntegerField(primary_key=True, serialize=False)),
                ('account_balance', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
