# Generated by Django 2.2.5 on 2020-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_detail',
            name='account_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
