# Generated by Django 2.2.5 on 2020-02-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200223_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Account_detail',
        ),
    ]
