# Generated by Django 2.2.5 on 2020-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200224_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
